runtime: php55
api_version: 1

instance_class: F1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

skip_files:
- ^(.*/)?\..*$
- ^(.*/)?googleDrive/.*$
- ^(.*/)?composer[^/]+$
- ^(.*/)?old_files/.*$

handlers:
#post sensor data
- url: /postData$
  script: postData.php

#/*.php
- url: /([^/]+\.php)$
  script: \1

#convertor
- url: /convertData.php$
  script: convertData.php

#favicon
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  application_readable: true

#/*.html
- url: /([^/]+\.html)$
  static_files: \1
  upload: ([^/]+\.html)$
  application_readable: true

